// desktop/renderer/panel-react/src/tabs/Practice.jsx
// React 版「专项练习」（手写/算法题库 + CodeMirror 6 判题编辑器）
// 前端三态 CodeMirror 6 升级工单：原生 panel（practice-editor.ts 已改）→ 本文件（React 侧）。
// 数据源复用同一后端 HTTP 路由（api.js → api-client 解析基址，不硬编码端口）：
//   /api/challenges（列表，分类/难度走后端，done/搜索前端过滤）→ /api/challenges/detail（题干+骨架）
//   → /api/challenges/run（判题）→ /api/challenges/mark-done / mark-wrong（闭环回流）。
// ⚛️ React 特性：useRef 持有 CodeMirror EditorView（useEffect 创建 + 卸载 destroy，切 tab 不泄漏 DOM），
//   useMemo 派生筛选结果（状态驱动差量渲染，替代原生 innerHTML 全量重建）。
import { useEffect, useMemo, useRef, useState } from "react";
import { EditorView, keymap } from "@codemirror/view";
import { EditorState } from "@codemirror/state";
import { basicSetup } from "codemirror";
import { javascript } from "@codemirror/lang-javascript";
import { oneDark } from "@codemirror/theme-one-dark";
import { indentWithTab } from "@codemirror/commands";
import { api } from "../api.js";

const DIFF_LABEL = {
  1: ["简单", "#2f7a4a"],
  2: ["中等", "#9a5b00"],
  3: ["困难", "#b91c1c"],
};
// 频率热度用 🔥 星标（与原生 panel-rest.js 同口径：最多 3 个）
const freqStars = (n) => "🔥".repeat(Math.max(0, Math.min(3, Number(n) || 0)));
// 筛选 chip 样式（panel.css 无 .oj-cat-chip 定义——仿原生 activeChip 内联：激活=紫色渐变，非激活=半透明描边）
const chipStyle = (active) => (active
  ? { background: "linear-gradient(135deg,#8a5adc,#6d4fd8)", color: "#fff", borderRadius: 6, padding: "4px 10px", border: "none", cursor: "pointer", fontSize: 12 }
  : { background: "rgba(109,79,216,.08)", color: "#5d48b8", border: "1px solid rgba(109,79,216,.25)", borderRadius: 6, padding: "4px 10px", cursor: "pointer", fontSize: 12 });

/** 判题结果展示（逐条断言 + 耗时 + console + tip + reflow 回流） */
function ResultView({ result }) {
  if (!result) return null;
  const pass = !!(result.ok && result.success);
  const tests = result.tests || [];
  const logs = result.logs || [];
  const rf = result.reflow || {};
  return (
    <div className="rf-card" style={{ borderColor: pass ? "rgba(58,141,90,.35)" : "rgba(185,28,28,.35)" }}>
      <div style={{ fontWeight: 700, color: pass ? "#2f7a4a" : "#b91c1c" }}>
        {pass ? "🎉 全部通过 ✅" : "❌ 有测试未通过"}
        <span style={{ fontWeight: 400, color: "#5a5678", fontSize: 12 }}> ⏱ {result.durationMs || 0} ms · {tests.length} 个测试</span>
      </div>
      {/* 逐条断言：✅/❌ + label（失败必须如实可见，不乐观假成功） */}
      {tests.map((t, i) => (
        <div key={i} style={{ fontSize: 12, lineHeight: 1.6, color: t.passed ? "#2f7a4a" : "#b91c1c" }}>
          {t.passed ? "✅" : "❌"} {t.label}
        </div>
      ))}
      {result.error && <div style={{ fontSize: 12, color: "#b91c1c", marginTop: 4 }}>⚠️ {result.error}</div>}
      {logs.length > 0 && (
        <div style={{ marginTop: 6 }}>
          <div style={{ fontSize: 11, color: "#5a5678" }}>— console 输出 —</div>
          <pre style={{ margin: 4, fontSize: 11, lineHeight: 1.5, whiteSpace: "pre-wrap", wordBreak: "break-all", color: "#8a5adc" }}>{logs.join("\n")}</pre>
        </div>
      )}
      {result.tip && <div style={{ fontSize: 12, color: "#9a5b00", marginTop: 4 }}>💡 {result.tip}</div>}
      {/* reflow：服务端判题已自动回流，面板如实显示去向；回流失败也要报 */}
      {rf.error && <div style={{ fontSize: 12, color: "#b91c1c", marginTop: 4 }}>⚠️ 回流失败：{String(rf.error).slice(0, 80)}</div>}
      {rf.done && <div style={{ fontSize: 12, color: "#2f7a4a", marginTop: 4 }}>♻️ 已自动标记完成（题库进度 + 学习进度回流）</div>}
      {rf.wrong && <div style={{ fontSize: 12, color: "#9a5b00", marginTop: 4 }}>♻️ 已记入错题 + 复习卡（wrong_count + 薄弱点回流，到期会提醒复习）</div>}
    </div>
  );
}

/** 展开的单题判题区：CodeMirror 6 编辑器 + 判题 + 标记完成/记错题 */
function ChallengeEditor({ challenge, onChanged, onNotify }) {
  const [detail, setDetail] = useState(null);
  const [busy, setBusy] = useState(false);
  const [marking, setMarking] = useState(false);
  const [err, setErr] = useState("");
  const [msg, setMsg] = useState("");
  const [result, setResult] = useState(null);
  // useRef 持有 CodeMirror 实例（不放进 state，避免无关渲染重建；卸载走 cleanup destroy）
  const hostRef = useRef(null);
  const viewRef = useRef(null);

  // 加载题干（含 skeleton/testCode）
  useEffect(() => {
    let alive = true;
    api(`/api/challenges/detail?id=${encodeURIComponent(challenge.id)}`)
      .then((j) => { if (alive && j?.ok) setDetail(j.detail); })
      .catch((e) => { if (alive) setErr("加载题干失败：" + String(e?.message || e).slice(0, 80)); })
      .finally(() => {});
    return () => { alive = false; };
  }, [challenge.id]);

  // CodeMirror 6 编辑器：挂载（拿到骨架）时 new EditorView，卸载/切 tab 时 destroy()
  useEffect(() => {
    if (!detail?.skeleton || !hostRef.current) return;
    let view = null;
    try {
      view = new EditorView({
        parent: hostRef.current,
        state: EditorState.create({
          doc: detail.skeleton,
          extensions: [
            basicSetup,        // 行号/历史/折叠/括号匹配/自动补全/搜索 一次到位
            javascript(),      // JS 语法高亮（题库是 JS 判题）
            oneDark,           // 深色主题（与判题结果区同色系）
            keymap.of([indentWithTab]), // Tab 缩进（默认 Tab 会跳焦）
            // Ctrl/Cmd+Enter → 运行判题（与原生 practice-editor.ts 一致）
            keymap.of([{ key: "Mod-Enter", preventDefault: true, run: () => { runJudgement(); return true; } }]),
            EditorView.theme({
              "&": { fontSize: "12px", height: "160px", border: "1px solid rgba(109,79,216,.3)", borderRadius: "6px", background: "#1e1e2e" },
              ".cm-scroller": { fontFamily: 'Consolas, Menlo, monospace', lineHeight: "1.55", overflow: "auto" },
              ".cm-content": { caretColor: "#c7a6ff" },
              "&.cm-focused": { outline: "none", borderColor: "rgba(109,79,216,.55)" },
            }),
          ],
        }),
      });
      viewRef.current = view;
    } catch (e) {
      // CodeMirror 在部分环境（如 jsdom 无布局测量）可能失败——如实报，不让编辑器卡死面板
      setErr("编辑器初始化失败：" + String(e?.message || e).slice(0, 80));
    }
    return () => {
      // 卸载清理：destroy() EditorView，防切 tab 泄漏原生 DOM/事件
      if (view) { view.destroy(); viewRef.current = null; }
    };
  }, [detail?.id]);

  // ▶ 运行判题：逐条断言如实渲染（结果区见 ResultView）
  async function runJudgement() {
    const code = viewRef.current?.state.doc.toString() || "";
    if (!code.trim()) { setErr("⚠️ 先写代码再判题"); return; }
    setBusy(true); setErr(""); setMsg("");
    try {
      const j = await api("/api/challenges/run", { method: "POST", body: { id: challenge.id, userCode: code } });
      // 失败必须如实可见：j.success 为 false 也渲染（不依赖 HTTP 是否 200）
      setResult(j);
      if (j?.success && j?.reflow?.error) setMsg("判题通过，但回流失败：" + String(j.reflow.error).slice(0, 60));
    } catch (e) {
      setErr("判题异常：" + String(e?.message || e).slice(0, 80));
    } finally {
      setBusy(false);
    }
  }

  // 标记完成 / 记错题：返回 ok:false（或抛 HTTP 错误）时如实提示，不假装成功
  async function doMark(ep, okText) {
    setMarking(true); setErr("");
    try {
      const j = await api(ep, { method: "POST", body: { id: challenge.id } });
      if (j?.ok) {
        onNotify?.(j.title || challenge.title, okText);
        onChanged(); // 刷新列表（done/wrongCount 徽标）
        setMsg(`${j.message || okText}`);
      } else {
        setErr(String(j?.error || "操作失败").slice(0, 80));
      }
    } catch (e) {
      // api-client 对非 2xx 抛带 status 的 Error——mark-done/mark-wrong 失败（404 ok:false）落这里
      setErr(String(e?.message || e).slice(0, 80));
    } finally {
      setMarking(false);
    }
  }

  const [dl] = DIFF_LABEL[detail?.difficulty] || ["难度" + (detail?.difficulty || "?"), "#5a5678"];
  const catLabel = detail?.category === "handwrite" ? "手写" : "算法";

  return (
    <div className="rf-card">
      <div className="rf-muted" style={{ fontWeight: 700, color: "#5d48b8" }}>
        📖 {detail?.title || challenge.title}
        <span className="rf-muted" style={{ fontWeight: 400 }}> [{catLabel} · {dl} · 建议 {detail?.timeLimit || 10} 分钟内]</span>
      </div>
      <pre className="rf-report" style={{ whiteSpace: "pre-wrap", marginTop: 4 }}>{detail?.description || "（本题暂无题干说明）"}</pre>
      {err && <div className="rf-muted rf-chip-warn">⚠️ {err}</div>}
      <div ref={hostRef} />
      <div style={{ display: "flex", gap: 6, marginTop: 8, flexWrap: "wrap", alignItems: "center" }}>
        <button type="button" className="rf-btn rf-btn-primary" disabled={busy || marking} onClick={runJudgement}>
          {busy ? "⏳ 判题中…" : "▶ 运行判题"}
        </button>
        {/* 标记完成/记错题：经同一路由 + 如实反馈 ok:false / 错误体 */}
        <button type="button" className="rf-btn" disabled={marking || busy || !result?.success}
          title={result?.success ? "所有测试通过，标记完成（计入学习进度）" : "需先判题且全部通过"} onClick={() => doMark("/api/challenges/mark-done", "已标记完成，进度 +1")}>
          ✅ 全部通过，标记完成
        </button>
        <button type="button" className="rf-btn" disabled={marking || busy} title="做错了，记入薄弱点 + 复习卡" onClick={() => doMark("/api/challenges/mark-wrong", "已记入薄弱点，复习阶段优先补")}>
          ❌ 不会
        </button>
        {msg && <span className="rf-muted" style={{ fontSize: 12 }}>{msg}</span>}
        <span className="rf-muted" style={{ fontSize: 11 }}>⌨️ Ctrl/Cmd + Enter 运行判题</span>
      </div>
      <ResultView result={result} />
    </div>
  );
}

export function PracticePanel() {
  const [list, setList] = useState([]);
  const [stats, setStats] = useState({ total: 0, done: 0 });
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState("");
  const [cat, setCat] = useState("");        // ""全部 / handwrite / algorithm（走后端）
  const [diff, setDiff] = useState(0);       // 0全部 / 1/2/3（走后端）
  const [done, setDone] = useState(0);       // 0全部 / 1未做 / 2已做（前端过滤）
  const [search, setSearch] = useState(""); // 搜索（前端过滤：标题/描述/ID）
  const [expandedId, setExpandedId] = useState(null);

  // 拉题库列表（分类/难度走后端过滤；done/搜索前端过滤）
  async function load() {
    setBusy(true); setErr("");
    try {
      const qs = new URLSearchParams();
      if (cat) qs.set("category", cat);
      if (diff) qs.set("difficulty", String(diff));
      const j = await api("/api/challenges?" + qs.toString());
      if (j?.ok === false) { setErr(String(j?.error || "题库加载失败").slice(0, 80)); return; }
      setList(j.list || []);
      setStats({ total: j.total ?? 0, done: j.done ?? 0 });
    } catch (e) {
      setErr("题库加载异常：" + String(e?.message || e).slice(0, 80));
    } finally {
      setBusy(false);
    }
  }
  useEffect(() => { load(); }, [cat, diff]);

  // 派生筛选（useMemo：done 态 + 关键词，状态驱动差量过滤）
  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    let arr = list.filter((p) =>
      (!done || (done === 1 ? !p.done : p.done)) &&
      (!q || `${p.title}\n${p.description || ""}\n${p.id}`.toLowerCase().includes(q))
    );
    // 排序同原生：未做在前 → 频率降序 → 难度升序
    arr = [...arr].sort((a, b) => (Number(a.done) - Number(b.done)) || (Number(b.frequency) - Number(a.frequency)) || (Number(a.difficulty) - Number(b.difficulty)));
    return arr;
  }, [list, done, search]);

  const pct = stats.total ? Math.round((stats.done / stats.total) * 100) : 0;

  return (
    <div className="rf-stack">
      <div className="rf-card">
        <div className="rf-head">
          <span className="rf-title">✍️ 专项练习 · React 版</span>
          <button className="rf-btn" onClick={load} disabled={busy}>{busy ? "刷新中…" : "🔄 刷新"}</button>
        </div>
        <div className="rf-muted">
          📦 共 {stats.total} 道 · 已完成 {stats.done}（{pct}%）· 本地沙箱判题，无需登录
        </div>

        {/* 工具栏：搜索 + 完成状态 + 分类 + 难度（搜索/done 前端过滤，cat/diff 走后端） */}
        <div className="rf-toolbar" style={{ flexWrap: "wrap", gap: 6, marginTop: 8 }}>
          <input className="rf-input" placeholder="🔍 搜索标题/描述/ID…" value={search}
            aria-label="搜索题目" onChange={(e) => setSearch(e.target.value)} style={{ maxWidth: 200 }} />
          {[
            [0, "📋 全部"], [1, "🆕 未做"], [2, "✅ 已做"],
          ].map(([v, lbl]) => (
            <button key={v} type="button" style={chipStyle(done === v)}
              onClick={() => setDone(v)}>{lbl}</button>
          ))}
          <span style={{ width: 1, height: 14, background: "rgba(109,79,216,.18)", alignSelf: "center" }} />
          {[
            ["", "全部"], ["handwrite", "✍️ 手写"], ["algorithm", "🧮 算法"],
          ].map(([v, lbl]) => (
            <button key={v || "all"} type="button" style={chipStyle(cat === v)}
              onClick={() => { setCat(v); setExpandedId(null); }}>{lbl}</button>
          ))}
          {[
            [0, "全部"], [1, "简单"], [2, "中等"], [3, "困难"],
          ].map(([v, lbl]) => (
            <button key={v} type="button" style={chipStyle(diff === v)}
              onClick={() => { setDiff(v); setExpandedId(null); }}>{lbl}</button>
          ))}
        </div>
        {(search || done) && (
          <div className="rf-muted" style={{ fontSize: 11, marginTop: 6 }}>命中 {filtered.length} / {list.length}</div>
        )}
      </div>

      {err && <div className="rf-card"><div className="rf-muted rf-chip-warn">⚠️ {err}</div></div>}

      {filtered.length === 0 ? (
        <div className="rf-card rf-muted">📭 当前筛选下没有题目（可换分类/难度或清掉搜索）</div>
      ) : (
        filtered.map((p) => {
          const [dl, dc] = DIFF_LABEL[p.difficulty] || ["难度" + p.difficulty, "#5a5678"];
          const expanded = expandedId === p.id;
          return (
            <div key={p.id} className="rf-card">
              <div
                role="button" tabIndex={0} aria-label={`展开 ${p.title}`} title="点击展开/收起题干与编辑器"
                onClick={() => setExpandedId(expanded ? null : p.id)}
                onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); setExpandedId(expanded ? null : p.id); } }}
                style={{ cursor: "pointer", display: "flex", flexWrap: "wrap", gap: 6, alignItems: "center" }}
              >
                <span className="job-badge" style={{ background: p.category === "handwrite" ? "rgba(58,141,90,.12)" : "rgba(109,79,216,.12)", color: p.category === "handwrite" ? "#2f7d4e" : "#5d48b8" }}>
                  {p.category === "handwrite" ? "✍️手写" : "🧮算法"}
                </span>
                <span style={{ color: dc, fontSize: 11 }}>{dl}</span>
                <span title="面试出现频率" style={{ fontSize: 11 }}>{freqStars(p.frequency)}</span>
                <b style={{ fontSize: 12 }}>{p.title}</b>
                {p.done && <span style={{ color: "#2f7a4a", fontSize: 11 }}>✅ 已做</span>}
                {p.wrongCount > 0 && <span style={{ color: "#b91c1c", fontSize: 11 }}>答错 {p.wrongCount} 次</span>}
              </div>
              {expanded && (
                <ChallengeEditor challenge={p} onChanged={() => { setExpandedId(null); load(); }}
                  onNotify={(title, txt) => {
                    try { window.kanban.notify?.("✍️ 手写题", `「${title}」${txt}`); } catch { /* 通知失败不影响主流程 */ }
                  }} />
              )}
            </div>
          );
        })
      )}

      <div className="rf-muted">⚛️ React 特性：useRef 持有 CodeMirror 6 编辑器（useEffect 创建 / 卸载 destroy）+ useMemo 派生筛选</div>
    </div>
  );
}

// desktop/renderer/panel-vue-review/src/tabs/Practice.vue
<!-- Vue 版「专项练习」题库 + CodeMirror 6 判题（前端三态并行展示工单任务 3）：
     与原生 panel-rest.js 的题库区共用同一套后端路由 /api/challenges*，
     但编辑器用真正的 CodeMirror 6（不再手搓 textarea）。 -->
<!-- 🟢 Vue 特色：ref + onMounted/onUnmounted 管理 CodeMirror 生命周期（切 Tab 销毁不泄漏）+ computed 派生列表过滤 + v-model 驱动筛选/搜索 -->
<script setup>
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from "vue";
import { api } from "../api.js";
// CodeMirror 6：真正可判题的代码编辑器（三态一致升级的一部分）
import { basicSetup } from "codemirror";
import { EditorView, keymap } from "@codemirror/view";
import { EditorState } from "@codemirror/state";
import { indentWithTab } from "@codemirror/commands";
import { javascript } from "@codemirror/lang-javascript";
import { oneDark } from "@codemirror/theme-one-dark";

const DIFF_LABEL = { 1: ["简单", "#2f7a4a"], 2: ["中等", "#9a5b00"], 3: ["困难", "#b91c1c"] };
const freqStars = (n) => "🔥".repeat(Math.max(0, Math.min(3, Number(n) || 0)));

// ---------- 题库列表 ----------
const list = ref([]);
const total = ref(0);
const loading = ref(false);
const err = ref("");
// v-model 驱动的筛选：分类/难度走后端（与原生同口径），是否已做 + 搜索在前端 computed 过滤
const cat = ref("");   // "" | handwrite | algorithm
const diff = ref(0);   // 0 全部 | 1 简单 | 2 中等 | 3 困难
const doneFilter = ref(0); // 0 全部 | 1 未做 | 2 已做
const q = ref("");     // 搜索关键词（标题/描述/ID）

// 是否已做筛选是**前端过滤**：后端 /api/challenges 路由只透传 category/difficulty（见 practice.ts），
// 但 getChallenges 返回的每行都带 done 字段 → 在前端 computed 里按 done 过滤，与原生 chDone 同口径
const filtered = computed(() => {
  const query = q.value.trim().toLowerCase();
  return list.value.filter((c) => {
    if (doneFilter.value === 1 && c.done) return false;
    if (doneFilter.value === 2 && !c.done) return false;
    if (query && !`${c.title}\n${c.description || ""}\n${c.id}`.toLowerCase().includes(query)) return false;
    return true;
  });
});
const doneCount = computed(() => list.value.filter((c) => c.done).length);
const pct = computed(() => (total.value ? Math.round((doneCount.value / total.value) * 100) : 0));

async function loadChallenges() {
  loading.value = true;
  err.value = "";
  try {
    const sp = new URLSearchParams();
    if (cat.value) sp.set("category", cat.value);
    if (diff.value) sp.set("difficulty", String(diff.value));
    const qs = sp.toString();
    const j = await api("/api/challenges" + (qs ? `?${qs}` : ""));
    // 契约：/api/challenges 返回 { ok,total,done,left,list }（list 才是题目数组，不是 challenges）
    list.value = j?.list || [];
    total.value = j?.total ?? list.value.length;
  } catch (e) {
    err.value = "题库读取失败：" + String(e?.message || e).slice(0, 80);
    list.value = [];
  } finally {
    loading.value = false;
  }
}
onMounted(loadChallenges);

// ---------- 判题编辑器（CodeMirror 6） ----------
// selected：当前展开编题目的列表行；detail：其完整详情（含 skeleton/testCode）
const selected = ref(null);
const detail = ref(null);
const detailLoadErr = ref("");
const editorHost = ref(null);
// 编辑器 View 用裸 let 持有（CM 自建 DOM），不放进 reactive——避免代理污染 Lezer/View 内部对象
let editorView = null;
const running = ref(false);
const runErr = ref("");
const result = ref(null); // { success,error,tests,logs,durationMs,tip,reflow }
const markBusy = ref(false);
const markFlash = ref(""); // 标记完成的临时反馈（展开区内）
const rowFlash = ref({});  // 每行「已会/不会」的独立反馈（未展开行也要如实显示失败）

/** 点开某题：加载详情并挂编辑器（复用已加载列表行的 id） */
async function openChallenge(ch) {
  if (selected.value?.id === ch.id && detail.value) return; // 已展开无需重复
  selected.value = ch;
  detail.value = null;
  detailLoadErr.value = "";
  result.value = null;
  runErr.value = "";
  markFlash.value = "";
  try {
    const j = await api("/api/challenges/detail?id=" + encodeURIComponent(ch.id));
    if (!j?.ok) { detailLoadErr.value = String(j?.error || "加载失败").slice(0, 80); return; }
    detail.value = j.detail;
  } catch (e) {
    detailLoadErr.value = "详情加载失败：" + String(e?.message || e).slice(0, 80);
  }
}

async function closeEditor() {
  selected.value = null;
  detail.value = null;
  result.value = null;
}

/** 创建 CodeMirror 6 编辑器：basicSetup + JS 高亮 + oneDark + Tab 缩进 + Mod-Enter 判题 */
function createEditor(host, initial) {
  return new EditorView({
    parent: host,
    state: EditorState.create({
      doc: String(initial ?? ""),
      extensions: [
        basicSetup, // 行号/历史/折叠/括号匹配/自动补全/搜索 一次到位
        javascript(), // 题库是 JS 判题，词法用 JS 足矣
        oneDark, // 深色主题
        keymap.of([
          indentWithTab, // Tab 缩进（默认 Tab 跳焦点，不可用于编码）
          { key: "Mod-Enter", run: () => { runJudgement(); return true; } }, // Ctrl/Cmd+Enter 快速判题
        ]),
        EditorView.theme({
          "&": { fontSize: "12px", height: "200px", border: "1px solid rgba(109,79,216,.3)", borderRadius: "6px" },
          ".cm-scroller": { fontFamily: "Consolas, Menlo, monospace", lineHeight: "1.55", overflow: "auto" },
          ".cm-content": { caretColor: "#c7a6ff" },
          "&.cm-focused": { outline: "none", borderColor: "rgba(109,79,216,.55)" },
        }),
      ],
    }),
  });
}

/** 详情就绪且编辑器容器渲染后，挂/换编辑器（watch 保证拿到的是最新 detail 的 nextTick DOM） */
watch(detail, async (d, old) => {
  if (editorView) { editorView.destroy(); editorView = null; }
  if (!d) return;
  await nextTick();
  if (editorHost.value) editorView = createEditor(editorHost.value, d.skeleton || "");
});

// onUnmounted 必须 destroy：切 Tab（组件卸载）要释放 CM 的 DOM 监听/观测器，否则重复挂载会泄漏
onUnmounted(() => {
  if (editorView) { editorView.destroy(); editorView = null; }
});

// ---------- 判题 ----------
async function runJudgement() {
  if (!detail.value || !editorView) return;
  const userCode = editorView.state.doc.toString();
  if (!userCode.trim()) { runErr.value = "先写代码再判题"; return; }
  running.value = true;
  runErr.value = "";
  result.value = null;
  markFlash.value = "";
  try {
    const j = await api("/api/challenges/run", { method: "POST", body: { id: detail.value.id, userCode } });
    result.value = j;
    // 判题通过/失败服务端已自动回流（通过→done+进度；失败→wrong_count+薄弱点+复习卡）——
    // 这里如实展示回流结果，不做乐观更新假成功
    await loadChallenges(); // 刷新列表徽标（done/wrongCount）
  } catch (e) {
    runErr.value = "判题调用失败：" + String(e?.message || e).slice(0, 80);
  } finally {
    running.value = false;
  }
}

/** 回流结果文案（reflow：done→已自动标记完成；wrong→已记入错题+复习卡；error→如实显示） */
const reflowNote = computed(() => {
  const r = result.value?.reflow;
  if (!r) return "";
  if (r.error) return "⚠️ 回流失败：" + String(r.error).slice(0, 80);
  if (r.done) return "♻️ 已自动标记完成（题库进度 + 学习进度回流）";
  if (r.wrong) return "♻️ 已记入错题：wrong_count+1 + 薄弱点 + 复习卡";
  return "";
});

/** ✅ 标记完成：POST mark-done，服务端确认 ok 才更新徽标（失败如实显示，乐观不假成功）。
 *  既可点击列表行的「已会」（传 ch = 该行题目），也可判题通过后点编辑器里的「标记完成」（不传 → 用当前 detail） */
async function markDone(ch) {
  const target = ch || detail.value;
  if (!target?.id) return;
  markBusy.value = true;
  const setMsg = (msg) => { if (!ch) markFlash.value = msg; else rowFlash.value = { ...rowFlash.value, [target.id]: msg }; };
  setMsg("");
  try {
    const j = await api("/api/challenges/mark-done", { method: "POST", body: { id: target.id } });
    setMsg(j?.ok ? `✅ 「${j?.title || target.title}」已标记完成，进度 +1` : `⚠️ ${String(j?.error || "标记失败").slice(0, 80)}`);
    await loadChallenges();
  } catch (e) {
    setMsg("⚠️ 标记失败：" + String(e?.message || e).slice(0, 80));
  } finally {
    markBusy.value = false;
  }
}

/** ❌ 不会：POST mark-wrong，记入薄弱点 + 复习卡（同 markDone：列表行传 ch，编辑器内不传用 detail） */
async function markWrong(ch) {
  const target = ch || detail.value;
  if (!target?.id) return;
  markBusy.value = true;
  const setMsg = (msg) => { if (!ch) markFlash.value = msg; else rowFlash.value = { ...rowFlash.value, [target.id]: msg }; };
  setMsg("");
  try {
    const j = await api("/api/challenges/mark-wrong", { method: "POST", body: { id: target.id } });
    setMsg(j?.ok ? `♻️ 「${j?.title || target.title}」已记入薄弱点 + 复习卡` : `⚠️ ${String(j?.error || "记录失败").slice(0, 80)}`);
    await loadChallenges();
  } catch (e) {
    setMsg("⚠️ 记录失败：" + String(e?.message || e).slice(0, 80));
  } finally {
    markBusy.value = false;
  }
}
</script>

<template>
  <div class="rf-stack">
    <!-- 题库头部：统计 + 筛选 + 搜索 -->
    <div class="rf-card">
      <div class="rf-head">
        <b class="rf-title">✍️ 专项练习 · Vue 版</b>
        <span v-if="loading" class="rf-muted">⏳ 加载题库…</span>
        <span v-else class="rf-muted">📦 {{ total }} 道 · 已完成 {{ doneCount }}（{{ pct }}%）</span>
      </div>
      <div style="display:flex;gap:6px;margin-top:8px;flex-wrap:wrap">
        <input class="rf-input rf-grow" v-model="q" placeholder="搜索题目 / 描述 / ID…" aria-label="搜索题目" />
        <select class="rf-input" v-model="cat" aria-label="按分类筛选" @change="loadChallenges">
          <option value="">全部分类</option>
          <option value="handwrite">✍️ 手写</option>
          <option value="algorithm">🧮 算法</option>
        </select>
        <select class="rf-input" v-model="diff" aria-label="按难度筛选" @change="loadChallenges">
          <option :value="0">全部难度</option>
          <option :value="1">简单</option>
          <option :value="2">中等</option>
          <option :value="3">困难</option>
        </select>
        <select class="rf-input" v-model="doneFilter" aria-label="按是否已做筛选">
          <option :value="0">全部</option>
          <option :value="1">🆕 未做</option>
          <option :value="2">✅ 已做</option>
        </select>
      </div>
      <div v-if="err" class="rf-muted rf-chip-warn" style="margin-top:6px">⚠️ {{ err }}</div>
      <div v-if="q.trim() || doneFilter" class="rf-muted" style="margin-top:6px">命中 {{ filtered.length }}/{{ list.length }}</div>
    </div>

    <!-- 题库列表 -->
    <div v-if="!list.length && !loading" class="rf-card rf-muted">题库为空——运行 scripts/import-ai-career.mjs（手写题）或 scripts/import-codetop-top400.mjs（CodeTop 高频 400）导入</div>
    <div v-for="c in filtered" :key="c.id" class="rf-card">
      <div class="rf-row rf-row-start">
        <button type="button" class="rf-btn" style="flex:0 0 auto" @click="openChallenge(c)">✍️ 做题</button>
        <span class="rf-grow">
          <span style="display:flex;align-items:center;gap:6px;flex-wrap:wrap">
            <span class="rf-chip" :style="{ background: c.category === 'handwrite' ? 'rgba(58,141,90,.12)' : 'rgba(109,79,216,.12)', color: c.category === 'handwrite' ? '#2f7d4e' : '#5d48b8' }">{{ c.category === "handwrite" ? "✍️手写" : "🧮算法" }}</span>
            <span v-if="DIFF_LABEL[c.difficulty]" :style="{ color: DIFF_LABEL[c.difficulty][1], fontSize: '11px' }">{{ DIFF_LABEL[c.difficulty][0] }}</span>
            <span class="rf-muted" :title="`面试出现频率 ${c.frequency}`">{{ freqStars(c.frequency) }}</span>
            <b>{{ c.title }}</b>
            <span v-if="c.done" class="rf-chip rf-chip-ok">✅ 已做</span>
            <span v-if="c.wrongCount > 0" class="rf-chip" style="color:#b91c1c">答错 {{ c.wrongCount }} 次</span>
          </span>
        </span>
        <span v-if="!c.done" style="display:flex;gap:4px;flex-wrap:wrap">
          <button type="button" class="rf-btn" :disabled="markBusy" @click="markDone(c)">✅ 已会</button>
          <button type="button" class="rf-btn" :disabled="markBusy" @click="markWrong(c)">❌ 不会</button>
        </span>
      </div>
      <div v-if="rowFlash[c.id]" class="rf-muted rf-chip-warn" style="margin-top:6px">{{ rowFlash[c.id] }}</div>
      <div v-if="selected?.id === c.id" class="rf-sub" style="margin-top:8px">
        <!-- 题干 -->
        <div v-if="detailLoadErr" class="rf-muted rf-chip-warn">⚠️ {{ detailLoadErr }}</div>
        <div v-else-if="detail">
          <div class="rf-muted" style="display:block;white-space:pre-wrap;margin-bottom:8px;max-height:140px;overflow:auto">{{ detail.description || "(本题暂无题干说明)" }}</div>
          <div class="rf-muted" style="margin-bottom:4px;font-size:11px">建议 {{ detail.timeLimit || 10 }} 分钟内完成 · 在骨架里补全实现 · Ctrl/Cmd + Enter 快速判题</div>
          <!-- CodeMirror 6 挂载点（ref editorHost） -->
          <div ref="editorHost"></div>
          <div style="display:flex;gap:6px;margin-top:8px;flex-wrap:wrap;align-items:center">
            <button type="button" class="rf-btn rf-btn-primary" :disabled="running" @click="runJudgement">{{ running ? "⏳ 判题中…" : "▶ 运行判题" }}</button>
            <button v-if="result?.success" type="button" class="rf-btn" :disabled="markBusy" @click="markDone">✅ 全部通过，标记完成</button>
            <button v-if="result && !result.success" type="button" class="rf-btn" :disabled="markBusy" @click="markWrong">❌ 不会</button>
            <button type="button" class="rf-btn" @click="closeEditor">✖ 收起</button>
            <span v-if="markFlash" class="rf-muted" style="font-size:12px">{{ markFlash }}</span>
          </div>
          <div v-if="runErr" class="rf-muted rf-chip-warn" style="margin-top:6px">⚠️ {{ runErr }}</div>

          <!-- 判题结果：逐条断言 + 耗时 + console + tip + 回流。失败如实可见，不乐观假成功 -->
          <pre v-if="result" class="rf-report" style="white-space:pre-wrap;word-break:break-all;max-height:260px;overflow:auto;margin-top:8px">{{ result.success ? "🎉 全部通过 ✅" : "❌ 有测试未通过" }}
⏱ {{ result.durationMs }} ms · {{ (result.tests || []).length }} 个测试
{{ (result.tests || []).map((t) => `${t.passed ? "✅" : "❌"} ${t.label}`).join("\n") }}
{{ result.error ? "⚠️ " + result.error : "" }}{{ (result.logs || []).length ? "\n— console —\n" + result.logs.join("\n") : "" }}{{ result.tip ? "\n💡 " + result.tip : "" }}{{ reflowNote ? "\n" + reflowNote : "" }}</pre>
        </div>
      </div>
    </div>

    <div class="rf-muted">🟢 Vue 特性：ref + onMounted/onUnmounted 管理 CodeMirror 6 生命周期（切 Tab 销毁不泄漏）+ computed 派生列表过滤 + v-model 筛选与搜索</div>
  </div>
</template>
