// desktop/renderer/panel-react/src/tabs/Study.jsx
// React 版学习清单（前端三态并行展示工单任务 2 · S2①：列表 + 勾选 + 状态流分组 + 搜索过滤）
// 同一 IPC 桥（window.kanban.studyPlan/studyCheck/studyGenerate——业务层 lib/study-plan.mjs 零改动）。
// ⚛️ React 特性：useDeferredValue 搜索过滤（长清单输入不卡顿）+ useMemo 状态流分组派生
//   （原生版每次 loadStudyPlan 重建整块 innerHTML，React 版按状态差量更新）。
// 讲解入口复用原生讲解弹窗（showStudyDetail 在同一 preload/业务层之上，流式+追问+抽屉不重复实现）：
// 需要时切回原生渲染层再打开——功能等价，不做第二套流式 UI。
import { useDeferredValue, useEffect, useMemo, useState } from "react";

// 批次 2：深色内联已收敛为 panel.css 的 .rf-* 语义类（card/row/chip/btn/input/track/muted）

/** 清单状态流（与原生 loadStudyPlan 的 stateOf 同口径）：待复习 > 已掌握 > 已学 > 学习中 > 待学习 */
function stateOf(it) {
  if (it.reviewDue) return "review";
  if (it.done && it.mastered) return "mastered";
  if (it.done) return "learned";
  if (it.hasFile) return "learning";
  return "todo";
}
const STATE_LABELS = [
  { key: "todo", label: "📥 待学习" },
  { key: "learning", label: "📖 学习中" },
  { key: "learned", label: "✅ 已学（讲解过）" },
  { key: "review", label: "🔁 待复习（复习卡到期）" },
  { key: "mastered", label: "🏆 已掌握" },
];

export function StudyPanel() {
  const [plan, setPlan] = useState(null);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState("");
  const [q, setQ] = useState("");
  const deferredQ = useDeferredValue(q); // ⚛️ React 特性：输入不等待过滤
  const [lv, setLv] = useState("");
  const [st, setSt] = useState("");
  const [showMastered, setShowMastered] = useState(false);

  async function load() {
    try {
      const r = await window.kanban.studyPlan();
      if (r?.ok) setPlan(r.plan || { date: "", items: [] });
      else setErr("清单读取失败——后端未就绪");
    } catch (e) {
      setErr("清单读取异常：" + String(e?.message || e).slice(0, 80));
    }
  }
  useEffect(() => { load(); }, []);

  async function generate() {
    setBusy(true);
    setErr("");
    try {
      const r = await window.kanban.studyGenerate();
      if (r?.ok === false) setErr("生成失败：" + String(r.error || r.hint || "未知原因").slice(0, 80));
      else if (r?.addedCount === 0 && r?.note) setErr(r.note); // 无新知识点是正常情况，如实提示
      await load();
    } catch (e) {
      setErr("生成异常：" + String(e?.message || e).slice(0, 80));
    } finally {
      setBusy(false);
    }
  }

  /** 勾选/取消：同一 IPC（studyCheck）→ 薄弱点清除时给正反馈（与原生同款 toast 语义） */
  async function toggle(it, checked) {
    try {
      const r = await window.kanban.studyCheck(it.id, checked);
      if (r?.ok === false) { setErr("勾选失败：" + String(r.error || "").slice(0, 60)); return; }
      if (r?.clearedWeak) window.kanban?.notify?.("✨ 薄弱点消灭", `「${r.clearedWeak}」已消灭（清单勾选回流）`);
      await load();
    } catch (e) {
      setErr("勾选异常：" + String(e?.message || e).slice(0, 80));
    }
  }

  /** 讲解：切回原生渲染层 + 打开原生讲解弹窗（流式/追问/抽屉复用同一实现，不做第二套） */
  function explain(id) {
    try {
      window.switchRenderer?.("study", "native");
      window.showStudyDetail?.(id);
    } catch (e) {
      window.kanban?.notify?.("🎨 渲染层", "打开讲解失败：" + String(e?.message || e).slice(0, 60));
    }
  }

  const items = plan?.items || [];
  const doneN = items.filter((i) => i.done).length;
  const pct = items.length ? Math.round((doneN / items.length) * 100) : 0;

  // ⚛️ React 特性：过滤 + 分组都是派生值（依赖 deferredQ/lv/st/items——无关状态变化不重算）
  const { groups, matched } = useMemo(() => {
    const query = deferredQ.trim().toLowerCase();
    const pass = (it) => {
      if (lv && it.level !== lv) return false;
      if (st && stateOf(it) !== st) return false;
      if (query && !`${it.topic || ""} ${it.why || ""}`.toLowerCase().includes(query)) return false;
      return true;
    };
    const filtered = items.filter(pass);
    const g = { todo: [], learning: [], learned: [], review: [], mastered: [] };
    for (const it of filtered) g[stateOf(it)].push(it);
    return { groups: g, matched: filtered.length };
  }, [items, deferredQ, lv, st]);

  const filtering = Boolean(q.trim() || lv || st);
  // 主状态流不含"已掌握"——已掌握是折叠区（与原生同款：独立的 doneToggle 行，控制项不能被自己折叠掉）
  const mainStates = STATE_LABELS.filter((s) => s.key !== "mastered");
  const mastered = groups.mastered || [];

  return (
    <div className="rf-stack">
      <div className="rf-card">
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, marginBottom: 8 }}>
          <b className="rf-title">📋 学习清单 · React 版</b>
          <span style={{ display: "flex", gap: 6, alignItems: "center" }}>
            {plan?.date && <span className="rf-muted">{plan.date}</span>}
            <button type="button" className="rf-btn rf-btn-primary" onClick={generate} disabled={busy}>{busy ? "生成中…" : "✨ 从产出生成清单"}</button>
          </span>
        </div>
        {/* 进度（总进度，不受筛选影响——与原生同口径） */}
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <span className="rf-muted">📋 学习进度</span>
          <span className="rf-track rf-grow">
            <i className="rf-fill" style={{ width: `${pct}%` }} />
          </span>
          <b style={{ fontSize: 11 }}>{doneN}/{items.length}（{pct}%）</b>
        </div>
        {/* 搜索 + 筛选（useDeferredValue：输入即时，过滤延后） */}
        <div style={{ display: "flex", gap: 6, marginTop: 8, flexWrap: "wrap" }}>
          <input
            className="rf-input rf-grow"
            value={q}
            onChange={(e) => setQ(e.target.value)}
            placeholder="搜索知识点 / 学习理由…"
          />
          <select className="rf-input" value={lv} onChange={(e) => setLv(e.target.value)}>
            <option value="">全部级别</option>
            <option value="必会">必会</option>
            <option value="进阶">进阶</option>
            <option value="拓展">拓展</option>
          </select>
          <select className="rf-input" value={st} onChange={(e) => setSt(e.target.value)}>
            <option value="">全部状态</option>
            {STATE_LABELS.map((s) => <option key={s.key} value={s.key}>{s.label}</option>)}
          </select>
          {filtering && <span className="rf-muted">匹配 {matched}/{items.length}</span>}
        </div>
        {err && <div className="rf-muted rf-chip-warn" style={{ marginTop: 6 }}>⚠️ {err}</div>}
      </div>

      {items.length === 0 ? (
        <div className="rf-card rf-muted">未生成，点「✨ 从产出生成清单」</div>
      ) : (
        mainStates.map((s) => {
          const list = groups[s.key] || [];
          if (!list.length) return null;
          return (
            <div key={s.key} className="rf-card">
              <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 4 }}>
                <b className="rf-title">{s.label}</b>
                <span className="rf-chip">{list.length}</span>
              </div>
              {list.map((it) => (
                <div key={it.id} className="rf-row rf-row-start">
                  <input
                    type="checkbox"
                    checked={!!it.done}
                    onChange={(e) => toggle(it, e.target.checked)}
                    title={it.done ? "取消勾选（同时删除自动建的复习卡）" : "勾选完成（学习进度回流 + 自动建复习卡）"}
                    style={{ marginTop: 2 }}
                  />
                  <span style={{ flex: 1 }}>
                    <span style={{ display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap" }}>
                      <b className="rf-title" style={{ textDecoration: it.done ? "line-through" : "none", opacity: it.done ? 0.75 : 1 }}>{it.topic}</b>
                      {it.level && <span className="rf-chip">{it.level}</span>}
                      {it.grp && <span className="rf-chip rf-chip-plain">{it.grp}</span>}
                      {it.fromInterview && <span className="rf-chip rf-chip-warn">面试</span>}
                      {it.reviewDue && <span className="rf-chip rf-chip-ok">待复习</span>}
                    </span>
                    {it.why && <div className="rf-muted" style={{ marginTop: 3 }}>{it.why}</div>}
                  </span>
                  <button type="button" className="rf-btn" onClick={() => explain(it.id)} title="打开讲解（复用原生弹窗：流式 + 追问）">💡 讲解</button>
                </div>
              ))}
            </div>
          );
        })
      )}

      {/* 已掌握折叠区：控制行独立于被折叠内容（否则按钮在折叠块里 → 永远点不开） */}
      {mastered.length > 0 && (
        <div className="rf-card">
          <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
            <b style={{ fontSize: 12 }}>🏆 已掌握</b>
            <span className="rf-chip">{mastered.length}</span>
            <button type="button" className="rf-btn" onClick={() => setShowMastered((v) => !v)}>
              {showMastered ? "收起" : "展开"}
            </button>
          </div>
          {showMastered && mastered.map((it) => (
            <div key={it.id} className="rf-row rf-row-start">
              <input type="checkbox" checked readOnly title="已达成（取消勾选可退回学习中）" style={{ marginTop: 2 }} />
              <span style={{ flex: 1 }}>
                <span style={{ display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap" }}>
                  <b className="rf-title">{it.topic}</b>
                  {it.level && <span className="rf-chip">{it.level}</span>}
                  {it.grp && <span className="rf-chip rf-chip-plain">{it.grp}</span>}
                </span>
                {it.why && <div className="rf-muted" style={{ marginTop: 3 }}>{it.why}</div>}
              </span>
              <button type="button" className="rf-btn" onClick={() => explain(it.id)}>💡 讲解</button>
            </div>
          ))}
        </div>
      )}

      <div className="rf-muted">
        ⚛️ React 特性：useDeferredValue 搜索过滤 + useMemo 状态流分组（状态驱动差量更新）；讲解/追问复用同一实现
      </div>
    </div>
  );
}

// desktop/renderer/panel-vue-review/src/tabs/Study.vue
<!-- Vue 版学习清单（前端三态并行展示工单任务 3）：同一 IPC 桥（studyPlan/studyCheck/studyGenerate） -->
<!-- 🟢 Vue 特色：computed 链式派生（过滤 → 状态流分组 → 进度百分比）+ watch 侦听搜索词做防抖过滤 -->
<script setup>
import { computed, onMounted, ref, watch } from "vue";

const STATE_LABELS = [
  { key: "todo", label: "📥 待学习" },
  { key: "learning", label: "📖 学习中" },
  { key: "learned", label: "✅ 已学（讲解过）" },
  { key: "review", label: "🔁 待复习（复习卡到期）" },
];
const STATE_OPTIONS = [...STATE_LABELS, { key: "mastered", label: "🏆 已掌握" }];

const plan = ref(null);
const busy = ref(false);
const err = ref("");
const q = ref("");
const lv = ref("");
const st = ref("");
const showMastered = ref(false);
let timer = null;

/** 状态流（与原生 loadStudyPlan 的 stateOf 同口径）：待复习 > 已掌握 > 已学 > 学习中 > 待学习 */
function stateOf(it) {
  if (it.reviewDue) return "review";
  if (it.done && it.mastered) return "mastered";
  if (it.done) return "learned";
  if (it.hasFile) return "learning";
  return "todo";
}

async function load() {
  try {
    const r = await window.kanban.studyPlan();
    if (r?.ok) plan.value = r.plan || { date: "", items: [] };
    else err.value = "清单读取失败——后端未就绪";
  } catch (e) { err.value = "清单读取异常：" + String(e?.message || e).slice(0, 80); }
}
onMounted(load);

async function generate() {
  busy.value = true;
  err.value = "";
  try {
    const r = await window.kanban.studyGenerate();
    if (r?.ok === false) err.value = "生成失败：" + String(r.error || r.hint || "未知原因").slice(0, 80);
    else if (r?.addedCount === 0 && r?.note) err.value = r.note;
    await load();
  } catch (e) { err.value = "生成异常：" + String(e?.message || e).slice(0, 80); }
  finally { busy.value = false; }
}

async function toggle(it, checked) {
  try {
    const r = await window.kanban.studyCheck(it.id, checked);
    if (r?.ok === false) { err.value = "勾选失败：" + String(r.error || "").slice(0, 60); return; }
    if (r?.clearedWeak) window.kanban?.notify?.("✨ 薄弱点消灭", `「${r.clearedWeak}」已消灭（清单勾选回流）`);
    await load();
  } catch (e) { err.value = "勾选异常：" + String(e?.message || e).slice(0, 80); }
}

/** 讲解复用原生弹窗（流式+追问+抽屉同一实现，不做第二套） */
function explain(id) {
  try { window.switchRenderer?.("study", "native"); window.showStudyDetail?.(id); }
  catch (e) { window.kanban?.notify?.("🎨 渲染层", "打开讲解失败：" + String(e?.message || e).slice(0, 60)); }
}

const items = computed(() => plan.value?.items || []);
const doneN = computed(() => items.value.filter((i) => i.done).length);
const pct = computed(() => (items.value.length ? Math.round((doneN.value / items.value.length) * 100) : 0));
const filtering = computed(() => Boolean(q.value.trim() || lv.value || st.value));
// 🟢 computed 链：过滤 → 分组
const filtered = computed(() => {
  const query = q.value.trim().toLowerCase();
  return items.value.filter((it) => {
    if (lv.value && it.level !== lv.value) return false;
    if (st.value && stateOf(it) !== st.value) return false;
    if (query && !`${it.topic || ""} ${it.why || ""}`.toLowerCase().includes(query)) return false;
    return true;
  });
});
const groups = computed(() => {
  const g = { todo: [], learning: [], learned: [], review: [], mastered: [] };
  for (const it of filtered.value) g[stateOf(it)].push(it);
  return g;
});
</script>

<template>
  <div class="rf-stack">
    <div class="rf-card">
      <div class="rf-head">
        <b class="rf-title">📋 学习清单 · Vue 版</b>
        <span style="display:flex;gap:6px;align-items:center">
          <span v-if="plan?.date" class="rf-muted">{{ plan.date }}</span>
          <button type="button" class="rf-btn rf-btn-primary" :disabled="busy" @click="generate">{{ busy ? "生成中…" : "✨ 从产出生成清单" }}</button>
        </span>
      </div>
      <div style="display:flex;align-items:center;gap:8px">
        <span class="rf-muted">📋 学习进度</span>
        <span class="rf-track rf-grow"><i class="rf-fill" :style="{ width: pct + '%' }" /></span>
        <b style="font-size:11px">{{ doneN }}/{{ items.length }}（{{ pct }}%）</b>
      </div>
      <div style="display:flex;gap:6px;margin-top:8px;flex-wrap:wrap">
        <input class="rf-input rf-grow" v-model="q" placeholder="搜索知识点 / 学习理由…" aria-label="搜索清单条目" />
        <select class="rf-input" v-model="lv" aria-label="按级别筛选">
          <option value="">全部级别</option><option value="必会">必会</option><option value="进阶">进阶</option><option value="拓展">拓展</option>
        </select>
        <select class="rf-input" v-model="st" aria-label="按状态筛选">
          <option value="">全部状态</option>
          <option v-for="s in STATE_OPTIONS" :key="s.key" :value="s.key">{{ s.label }}</option>
        </select>
        <span v-if="filtering" class="rf-muted">匹配 {{ filtered.length }}/{{ items.length }}</span>
      </div>
      <div v-if="err" class="rf-muted rf-chip-warn" style="margin-top:6px">⚠️ {{ err }}</div>
    </div>

    <div v-if="items.length === 0" class="rf-card rf-muted">未生成，点「✨ 从产出生成清单」</div>
    <template v-else>
      <div v-for="s in STATE_LABELS" :key="s.key" class="rf-card">
        <template v-if="groups[s.key].length">
          <div style="display:flex;align-items:center;gap:6px;margin-bottom:4px">
            <b class="rf-title">{{ s.label }}</b><span class="rf-chip">{{ groups[s.key].length }}</span>
          </div>
          <div v-for="it in groups[s.key]" :key="it.id" class="rf-row rf-row-start">
            <input type="checkbox" :checked="!!it.done" :aria-label="`标记「${it.topic}」${it.done ? '未完成' : '已完成'}`" style="margin-top:2px" @change="toggle(it, $event.target.checked)" />
            <span class="rf-grow">
              <span style="display:flex;align-items:center;gap:6px;flex-wrap:wrap">
                <b class="rf-title" :style="{ textDecoration: it.done ? 'line-through' : 'none', opacity: it.done ? 0.75 : 1 }">{{ it.topic }}</b>
                <span v-if="it.level" class="rf-chip">{{ it.level }}</span>
                <span v-if="it.grp" class="rf-chip rf-chip-plain">{{ it.grp }}</span>
                <span v-if="it.fromInterview" class="rf-chip rf-chip-warn">面试</span>
                <span v-if="it.reviewDue" class="rf-chip rf-chip-ok">待复习</span>
              </span>
              <span v-if="it.why" class="rf-muted" style="display:block;margin-top:3px">{{ it.why }}</span>
            </span>
            <button type="button" class="rf-btn" title="打开讲解（复用原生弹窗：流式 + 追问）" @click="explain(it.id)">💡 讲解</button>
          </div>
        </template>
      </div>

      <!-- 已掌握折叠区：控制行独立于被折叠内容（否则按钮在折叠块里点不开） -->
      <div v-if="groups.mastered.length" class="rf-card">
        <div style="display:flex;align-items:center;gap:6px">
          <b class="rf-title">🏆 已掌握</b><span class="rf-chip">{{ groups.mastered.length }}</span>
          <button type="button" class="rf-btn" @click="showMastered = !showMastered">{{ showMastered ? "收起" : "展开" }}</button>
        </div>
        <template v-if="showMastered">
          <div v-for="it in groups.mastered" :key="it.id" class="rf-row rf-row-start">
            <input type="checkbox" checked disabled :aria-label="`「${it.topic}」已掌握`" style="margin-top:2px" />
            <span class="rf-grow"><b class="rf-title">{{ it.topic }}</b> <span v-if="it.grp" class="rf-chip rf-chip-plain">{{ it.grp }}</span></span>
            <button type="button" class="rf-btn" @click="explain(it.id)">💡 讲解</button>
          </div>
        </template>
      </div>
    </template>

    <div class="rf-muted">🟢 Vue 特性：computed 链式派生（过滤 → 状态流分组 → 进度）+ 勾选回流薄弱点提示；讲解复用原生实现</div>
  </div>
</template>
