// desktop/renderer/panel-vue-review/src/tabs/Dashboard.vue
<!-- Vue 版求职驾驶舱（前端三态并行展示工单任务 3 起步：Vue 侧从只有复习扩到全 Tab） -->
<!-- 同一数据源 /api/dashboard（与 React 版、原生版同接口）；样式走 panel.css 的 .rf-* 语义词汇 -->
<!-- 🟢 Vue 特色：ref + computed 响应式派生（近 7 天峰值/进度百分比只在依赖变化时重算）+ watch 侦听数据更新 -->
<script setup>
import { computed, onMounted, ref, watch } from "vue";
import { api } from "../api.js";

const data = ref(null);
const busy = ref(false);
const err = ref("");
const at = ref("");

async function load() {
  busy.value = true;
  err.value = "";
  try {
    const j = await api("/api/dashboard");
    if (j?.ok) { data.value = j; at.value = new Date().toLocaleTimeString("zh-CN"); }
    else err.value = "后端未就绪——widget 启动后可刷新重试";
  } catch (e) {
    err.value = "加载失败：" + String(e?.message || e).slice(0, 80);
  } finally {
    busy.value = false;
  }
}
onMounted(load);
// 🟢 Vue 特色：watch 侦听——数据更新即重算派生（无需手动触发渲染）
watch(data, () => { /* 派生值由 computed 自动跟随；此处留作扩展点（如数据到了再播动画） */ });

const week = computed(() => data.value?.week || {});
const series = computed(() => data.value?.weekSeries || []);
const report = computed(() => data.value?.report || {});
const progress = computed(() => data.value?.progress || {});
// 🟢 computed 缓存：峰值只在 weekSeries 变化时重算
const maxAct = computed(() => Math.max(1, ...series.value.map((d) => (d.study || 0) + (d.review || 0) + (d.challenge || 0))));
const todayStr = new Date().toISOString().slice(0, 10);
const dayName = (date) => ["日", "一", "二", "三", "四", "五", "六"][new Date(date + "T00:00:00").getDay()] || date.slice(5);
const pctOf = (done, total) => (total ? Math.round((done / total) * 100) : 0);
const reportLines = computed(() => {
  const r = report.value, out = [];
  if (r.highlights?.length) out.push("✅ 本周亮点：" + r.highlights.join("、"));
  if (r.gaps?.length) out.push("⚠️ 待补：" + r.gaps.join("；"));
  return out;
});
const rows = computed(() => [
  { label: "📚 学习清单", done: progress.value.plan?.done, total: progress.value.plan?.total },
  { label: "✍️ 手写/算法题库", done: progress.value.challenges?.done, total: progress.value.challenges?.total },
  { label: "🔁 复习卡掌握", done: progress.value.review?.mastered, total: progress.value.review?.total },
]);
</script>

<template>
  <div class="rf-stack">
    <div class="rf-card">
      <div class="rf-head">
        <b class="rf-title">📊 求职驾驶舱 · Vue 版</b>
        <span style="display:flex;gap:6px;align-items:center">
          <span v-if="at" class="rf-muted">{{ at }} 更新</span>
          <button type="button" class="rf-btn" :disabled="busy" @click="load">{{ busy ? "刷新中…" : "🔄 刷新" }}</button>
        </span>
      </div>
      <div style="display:flex;flex-wrap:wrap;gap:6px">
        <span class="rf-stat">📚 学习完成 <b class="rf-num">{{ week.studyDone ?? 0 }}</b></span>
        <span class="rf-stat">🔁 复习 <b class="rf-num">{{ week.reviewDone ?? 0 }} 张</b></span>
        <span class="rf-stat">✍️ 刷题 <b class="rf-num">{{ week.challengeDone ?? 0 }} 道</b></span>
        <span class="rf-stat">⏱️ 专注 <b class="rf-num">{{ Math.round(((week.focusMinutes ?? 0) / 60) * 10) / 10 }} 小时</b></span>
        <span class="rf-stat">💼 投递 <b class="rf-num">{{ week.applyCount ?? 0 }} 家</b></span>
        <span class="rf-stat">🎤 面试 <b class="rf-num">{{ week.interviewCount ?? 0 }} 场</b></span>
      </div>
      <div v-if="err" class="rf-muted rf-chip-warn" style="margin-top:8px">⚠️ {{ err }}</div>
    </div>

    <div class="rf-card">
      <b class="rf-title">📈 近 7 天活动</b>
      <div class="rf-muted">绿=学习 · 紫=复习 · 蓝=刷题（柱高按峰值归一）</div>
      <div v-if="!series.length" class="rf-muted" style="margin-top:8px">📭 暂无活动数据</div>
      <div v-else style="display:flex;gap:6px;align-items:flex-end;margin-top:8px">
        <div v-for="d in series" :key="d.date" style="flex:1;text-align:center">
          <div style="display:flex;gap:2px;justify-content:center;align-items:flex-end;height:30px">
            <span class="rf-bar rf-bar-study" :style="{ height: Math.max(2, Math.round(((d.study || 0) / maxAct) * 26)) + 'px', opacity: d.study ? 1 : 0.25 }" :title="`学习 ${d.study || 0}`" />
            <span class="rf-bar rf-bar-review" :style="{ height: Math.max(2, Math.round(((d.review || 0) / maxAct) * 26)) + 'px', opacity: d.review ? 1 : 0.25 }" :title="`复习 ${d.review || 0}`" />
            <span class="rf-bar rf-bar-challenge" :style="{ height: Math.max(2, Math.round(((d.challenge || 0) / maxAct) * 26)) + 'px', opacity: d.challenge ? 1 : 0.25 }" :title="`刷题 ${d.challenge || 0}`" />
          </div>
          <div :class="d.date === todayStr ? 'rf-day rf-day-today' : 'rf-day'">{{ dayName(d.date) }}</div>
        </div>
      </div>
    </div>

    <div class="rf-card">
      <b class="rf-title">📝 本周复盘与下周建议</b>
      <pre class="rf-report">{{ reportLines.join("\n") }}{{ reportLines.length ? "\n\n" : "" }}{{ (report.suggestions || []).join("\n") || (reportLines.length ? "" : "📭 暂无建议") }}</pre>
    </div>

    <div class="rf-card">
      <b class="rf-title">📌 累计进度（闭环总览）</b>
      <div v-for="r in rows" :key="r.label" class="rf-row" style="align-items:center">
        <span class="rf-muted" style="width:110px">{{ r.label }}</span>
        <span class="rf-track rf-grow"><i class="rf-fill" :style="{ width: pctOf(r.done, r.total) + '%' }" /></span>
        <b style="font-size:11px">{{ r.done || 0 }}/{{ r.total || 0 }}</b>
      </div>
      <div style="display:flex;flex-wrap:wrap;gap:6px;margin-top:8px">
        <span class="rf-stat">🎯 方向 <b class="rf-num">{{ progress.direction || "未设置" }}</b></span>
        <span class="rf-stat">🔧 薄弱点 <b class="rf-num">{{ progress.weak ?? 0 }}</b></span>
        <span class="rf-stat">🔁 复习到期 <b class="rf-num">{{ progress.review?.due ?? 0 }}</b></span>
      </div>
    </div>

    <div class="rf-muted">🟢 Vue 特性：ref + computed 响应式派生（峰值/百分比只在依赖变化时重算）+ watch 侦听数据更新</div>
  </div>
</template>

// desktop/renderer/panel-react/src/tabs/Dashboard.jsx
// React 版求职驾驶舱（前端三态并行展示工单任务 2 · S1 数据展示型 Tab）
// 同一数据源 /api/dashboard（与原 panel-jobs.js 的 loadDashboard 同接口）——三态等价性由此保证。
// ⚛️ React 特性：useMemo 缓存近 7 天活动峰值（无关状态变化不重算）+ 组件化 <StatChip>/<ProgressRow>
//   （原生版是 innerHTML 拼串，每次刷新全量重建 DOM；React 版按状态差量更新）。
import { useEffect, useMemo, useState } from "react";
import { api } from "../api.js";

const S = {
  // 批次 2：深色内联已收敛为 panel.css 的 .rf-* 语义类（见 panel.css 样式词汇段）
  card: {},
  head: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, marginBottom: 8 },
  title: { fontSize: 13, fontWeight: 700 },
  muted: {},
  chipRow: { display: "flex", flexWrap: "wrap", gap: 6 },
  chip: {},
  num: { color: "#8fc7ff", fontSize: 14, fontWeight: 700 },
  btn: {},
  row: { display: "flex", alignItems: "center", gap: 8, fontSize: 12, marginTop: 6 },
  rowLabel: { width: 110 },
  track: { flex: 1 },
  rep: {},
  err: { fontSize: 12, color: "#e8c04a" },
};

/** 本周总览 chip（组件化：原生是模板串） */
function StatChip({ label, value }) {
  return (
    <div className="rf-stat">
      {label} <b className="rf-num">{value}</b>
    </div>
  );
}

/** 累计进度条（派生百分比在渲染期算——total 缺失时 0%，不除零） */
function ProgressRow({ label, done = 0, total = 0, color = "#8fc7ff" }) {
  const pct = total ? Math.round((done / total) * 100) : 0;
  return (
    <div className="rf-row">
      <span className="rf-muted">{label}</span>
      <span className="rf-track rf-grow">
        <i style={{ display: "block", height: "100%", width: `${pct}%`, background: color, borderRadius: 3 }} />
      </span>
      <b style={{ fontSize: 11 }}>
        {done}/{total}
      </b>
    </div>
  );
}

const DAY_NAMES = ["日", "一", "二", "三", "四", "五", "六"];

export function DashboardPanel() {
  const [data, setData] = useState(null);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState("");
  const [at, setAt] = useState("");

  async function load() {
    setBusy(true);
    setErr("");
    try {
      const j = await api("/api/dashboard");
      if (j?.ok) { setData(j); setAt(new Date().toLocaleTimeString("zh-CN")); }
      else setErr("后端未就绪——widget 启动后可刷新重试");
    } catch (e) {
      setErr("加载失败：" + String(e?.message || e).slice(0, 80));
    } finally {
      setBusy(false);
    }
  }

  useEffect(() => { load(); }, []);

  const week = data?.week || {};
  const series = data?.weekSeries || [];
  const report = data?.report || {};
  const progress = data?.progress || {};
  // ⚛️ React 特性：峰值只在 weekSeries 变化时重算（原生每次刷新都重算一遍并重建整块 DOM）
  const maxAct = useMemo(
    () => Math.max(1, ...series.map((d) => (d.study || 0) + (d.review || 0) + (d.challenge || 0))),
    [series]
  );
  const todayStr = new Date().toISOString().slice(0, 10);

  const reportLines = [];
  if (report.highlights?.length) reportLines.push(`✅ 本周亮点：${report.highlights.join("、")}`);
  if (report.gaps?.length) reportLines.push(`⚠️ 待补：${report.gaps.join("；")}`);

  return (
    <div className="rf-stack">
      <div className="rf-card">
        <div className="rf-head">
          <span className="rf-title">📊 求职驾驶舱 · React 版</span>
          <span style={{ display: "flex", alignItems: "center", gap: 8 }}>
            {at && <span className="rf-muted">{at} 更新</span>}
            <button className="rf-btn" onClick={load} disabled={busy}>{busy ? "刷新中…" : "🔄 刷新"}</button>
          </span>
        </div>
        <div className="rf-toolbar">
          <StatChip label="📚 学习完成" value={week.studyDone ?? 0} />
          <StatChip label="🔁 复习" value={`${week.reviewDone ?? 0} 张`} />
          <StatChip label="✍️ 刷题" value={`${week.challengeDone ?? 0} 道`} />
          <StatChip label="⏱️ 专注" value={`${Math.round(((week.focusMinutes ?? 0) / 60) * 10) / 10} 小时`} />
          <StatChip label="💼 投递" value={`${week.applyCount ?? 0} 家`} />
          <StatChip label="🎤 面试" value={`${week.interviewCount ?? 0} 场`} />
        </div>
        {err && <div style={{ ...S.err, marginTop: 8 }}>⚠️ {err}</div>}
      </div>

      <div className="rf-card">
        <div className="rf-title">📈 近 7 天活动</div>
        <div className="rf-muted">绿=学习 · 紫=复习 · 蓝=刷题 · 底部条=专注时长</div>
        {series.length === 0 ? (
          <div style={{ ...S.muted, marginTop: 8 }}>📭 暂无活动数据</div>
        ) : (
          <div style={{ display: "flex", gap: 6, alignItems: "flex-end", marginTop: 8 }}>
            {series.map((d) => {
              const isToday = d.date === todayStr;
              const bar = (v, color) => (
                <span
                  title={`${color.name} ${v}`}
                  style={{ width: 6, height: Math.max(2, Math.round(((v || 0) / maxAct) * 26)), background: v ? color.on : color.off, borderRadius: 2 }}
                />
              );
              const study = { on: "#3a8a5a", off: "rgba(58,138,90,.25)", name: "学习" };
              const review = { on: "#8a5adc", off: "rgba(138,90,220,.25)", name: "复习" };
              const challenge = { on: "#4a6fe0", off: "rgba(74,111,224,.25)", name: "刷题" };
              return (
                <div key={d.date} style={{ flex: 1, textAlign: "center" }}>
                  <div style={{ display: "flex", gap: 2, justifyContent: "center", alignItems: "flex-end", height: 30 }}>
                    {bar(d.study, study)}
                    {bar(d.review, review)}
                    {bar(d.challenge, challenge)}
                  </div>
                  <div
                    title={`专注 ${d.focus || 0} 分钟`}
                    style={{ height: 4, marginTop: 2, borderRadius: 2, background: d.focus ? "#8a5adc" : "rgba(138,90,220,.2)" }}
                  />
                  <div className={isToday ? "rf-day rf-day-today" : "rf-day"}>
                    {DAY_NAMES[new Date(d.date + "T00:00:00").getDay()] || d.date.slice(5)}
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

      <div className="rf-card">
        <div className="rf-title">📝 本周复盘与下周建议</div>
        <pre className="rf-report">
          {reportLines.join("\n")}
          {reportLines.length ? "\n\n" : ""}
          {(report.suggestions || []).join("\n") || (reportLines.length ? "" : "📭 暂无建议")}
        </pre>
      </div>

      <div className="rf-card">
        <div className="rf-title">📌 累计进度（闭环总览）</div>
        <ProgressRow label="📚 学习清单" done={progress.plan?.done} total={progress.plan?.total} />
        <ProgressRow label="✍️ 手写/算法题库" done={progress.challenges?.done} total={progress.challenges?.total} color="#4a6fe0" />
        <ProgressRow label="🔁 复习卡掌握" done={progress.review?.mastered} total={progress.review?.total} color="#3a8a5a" />
        <div style={{ ...S.chipRow, marginTop: 8 }}>
          <StatChip label="🎯 方向" value={progress.direction || "未设置"} />
          <StatChip label="🔧 薄弱点" value={progress.weak ?? 0} />
          <StatChip label="🔁 复习到期" value={progress.review?.due ?? 0} />
          <StatChip label="💼 未投" value={progress.jobs?.open ?? 0} />
          <StatChip label="📮 已投" value={progress.jobs?.applied ?? 0} />
        </div>
      </div>

      <div className="rf-muted">⚛️ React 特性：useMemo 缓存 7 天峰值 + 组件化 StatChip/ProgressRow（状态驱动差量更新）</div>
    </div>
  );
}
