// desktop/renderer/panel-vue-review/src/tabs/Jobs.vue
<!-- Vue 版校招（前端三态并行展示工单任务 3）：同一路由（/api/jobs/recommended、/api/jobs?status=、favorite、status） -->
<!-- 🟢 Vue 特色：v-model 表单（搜索/状态筛选）+ computed 派生可见列表与统计 + 收藏乐观更新 -->
<script setup>
import { computed, onMounted, ref, watch } from "vue";
import { api } from "../api.js";

const DIRECTION_LABEL = { frontend: "前端", agent: "AI Agent", fullstack: "全栈", backend: "后端", algorithm: "算法" };
const STATUS_LABEL = { ready: "📮 已投递", ready_bishi: "✍️ 待笔试", done: "✅ 已完成", archived: "🗄 已归档", new: "未处理" };
// 状态值与后端枚举一致（lib/jobs.ts setJobStatus 接受 new/ready/ready_bishi/done/archived）——
// 修复（闭环清查）：此前用 "none" → 「未处理」筛选恒空，且与原生面板（new）口径不一致；
// archived 为终态（归档，软删除），可与「恢复」组成闭环
const STATUS_FILTERS = [["", "全部"], ["ready", "📮 已投递"], ["ready_bishi", "✍️ 待笔试"], ["new", "未处理"], ["archived", "🗄 已归档"]];

const jobs = ref([]);
const status = ref("");   // v-model
const onlyFav = ref(false);
const q = ref("");        // v-model
const busy = ref(false);
const err = ref("");
const openJd = ref({});

async function load() {
  busy.value = true; err.value = "";
  try {
    const j = status.value ? await api(`/api/jobs?status=${encodeURIComponent(status.value)}`) : await api("/api/jobs/recommended");
    jobs.value = j?.recommended || j?.jobs || [];
  } catch (e) {
    err.value = "岗位读取失败：" + String(e?.message || e).slice(0, 80);
    jobs.value = [];
  } finally { busy.value = false; }
}
onMounted(load);
watch(status, load); // 状态筛选变化即重取（与原生同语义）

async function toggleFav(job) {
  const next = !job.favorite;
  jobs.value = jobs.value.map((x) => (x.id === job.id ? { ...x, favorite: next } : x)); // 乐观更新
  try { await api("/api/jobs/favorite", { method: "POST", body: { id: job.id, favorite: next } }); }
  catch (e) {
    jobs.value = jobs.value.map((x) => (x.id === job.id ? { ...x, favorite: !next } : x)); // 失败回滚
    window.kanban?.notify?.("⭐ 收藏失败", String(e?.message || e).slice(0, 60));
  }
}
async function setJobStatus(job, next) {
  try {
    await api("/api/jobs/status", { method: "POST", body: { id: job.id, status: next } });
    jobs.value = jobs.value.map((x) => (x.id === job.id ? { ...x, status: next } : x));
    if (next === "archived") window.kanban?.notify?.("🏢 校招岗位", "已归档（筛选里选「🗄 已归档」可恢复）");
  } catch (e) { err.value = "状态更新失败：" + String(e?.message || e).slice(0, 60); }
}
/** 归档（消失型操作 → 二次确认；Electron 渲染层 confirm 可用，prompt 会抛异常） */
function archiveJob(job) {
  if (!window.confirm(`归档「${job.company} ${job.title}」？归档后不再出现在未处理与推荐里。`)) return;
  setJobStatus(job, "archived");
}
/** agent 流程（JD 反推考点/按岗面试）复用原生渲染层，不做两套 */
function openInNative(kind) {
  window.switchRenderer?.("jobs", "native");
  window.kanban?.notify?.("🎨 渲染层", kind === "study" ? "已切回原生渲染层：请在原生界面执行「学考点」" : "已切回原生渲染层：请在原生界面执行「按岗面试」");
}

const visible = computed(() => {
  const query = q.value.trim().toLowerCase();
  return jobs.value.filter((j) => {
    if (onlyFav.value && !j.favorite) return false;
    if (!query) return true;
    return `${j.company || ""} ${j.title || ""} ${j.summary || ""}`.toLowerCase().includes(query);
  });
});
const stats = computed(() => ({
  total: jobs.value.length,
  fav: jobs.value.filter((j) => j.favorite).length,
  applied: jobs.value.filter((j) => j.status === "ready").length,
}));
</script>

<template>
  <div class="rf-stack">
    <div class="rf-card">
      <div class="rf-head">
        <b class="rf-title">🏢 校招岗位 · Vue 版</b>
        <span style="display:flex;gap:6px;align-items:center">
          <span class="rf-muted">{{ stats.total }} 个岗位 · 收藏 {{ stats.fav }} · 已投 {{ stats.applied }}</span>
          <button type="button" class="rf-btn" :disabled="busy" @click="load">{{ busy ? "刷新中…" : "🔄 刷新" }}</button>
        </span>
      </div>
      <div style="display:flex;gap:6px;flex-wrap:wrap;align-items:center">
        <input class="rf-input rf-grow" v-model="q" placeholder="搜索公司 / 岗位 / 摘要…" aria-label="搜索岗位" />
        <select class="rf-input" v-model="status" aria-label="按投递状态筛选">
          <option v-for="[v, label] in STATUS_FILTERS" :key="v" :value="v">{{ label }}</option>
        </select>
        <label class="rf-muted" style="display:flex;align-items:center;gap:4px">
          <input type="checkbox" v-model="onlyFav" aria-label="只看收藏岗位" /> 只看收藏
        </label>
        <button type="button" class="rf-btn" title="搜集校招等抓取操作在原生渲染层" @click="window.switchRenderer?.('jobs', 'native')">🔍 搜集校招（原生）</button>
      </div>
      <div v-if="err" class="rf-muted rf-chip-warn" style="margin-top:6px">⚠️ {{ err }}</div>
    </div>

    <div class="rf-card">
      <div v-if="!visible.length" class="rf-muted">
        {{ jobs.length === 0 ? "暂无岗位——点「🔍 搜集校招」（原生）抓取，或先在设置里填简历/方向" : "没有匹配的岗位，试试清空搜索或换筛选" }}
      </div>
      <div v-for="job in visible" :key="job.id" class="rf-row rf-row-start">
        <span class="rf-grow">
          <span style="display:flex;align-items:center;gap:6px;flex-wrap:wrap">
            <b class="rf-title">{{ job.company }}</b><span>{{ job.title }}</span>
            <span class="rf-chip">{{ DIRECTION_LABEL[job.direction] || job.direction || "未标方向" }}</span>
            <span class="rf-chip rf-chip-info">匹配 {{ job.match || "—" }}</span>
            <span v-if="job.favorite" class="rf-chip rf-chip-warn">⭐ 收藏</span>
            <span class="rf-chip rf-chip-plain">{{ STATUS_LABEL[job.status] || job.status || "未处理" }}</span>
          </span>
          <span v-if="job.jobType || job.deadline || job.bishiDate" class="rf-muted" style="display:block;margin-top:3px">
            <span v-if="job.jobType">{{ job.jobType }} </span>
            <span v-if="job.deadline">⏰ 截止 {{ job.deadline }} </span>
            <span v-if="job.bishiDate">📝 笔试 {{ job.bishiDate }}</span>
          </span>
          <span v-if="job.summary" class="rf-muted" style="display:block;margin-top:3px">{{ job.summary }}</span>
          <pre v-if="job.jdText && openJd[job.id]" class="rf-report rf-sub" style="margin-top:6px">{{ job.jdText }}</pre>
        </span>
        <span style="display:flex;gap:4px;flex-wrap:wrap;justify-content:flex-end">
          <button type="button" class="rf-btn" :aria-label="job.favorite ? `取消收藏 ${job.company}` : `收藏 ${job.company}`" @click="toggleFav(job)">{{ job.favorite ? "⭐" : "☆" }}</button>
          <button v-if="job.jdText" type="button" class="rf-btn" :aria-expanded="Boolean(openJd[job.id])" @click="openJd = { ...openJd, [job.id]: !openJd[job.id] }">📋 JD</button>
          <a v-if="job.applyUrl" class="rf-btn" :href="job.applyUrl" target="_blank" rel="noopener noreferrer">🔗 去投递</a>
          <!-- 归档=不感兴趣：不再提供「学考点/按岗面试」（后端按 id 查岗位时排除了归档行，否则点了必 404） -->
          <template v-if="job.status !== 'archived'">
            <button type="button" class="rf-btn" title="从 JD 反推考点加入学习清单（原生流程）" @click="openInNative('study')">📚 学考点</button>
            <button type="button" class="rf-btn" title="按该岗位 JD 开一场模拟面试（原生流程）" @click="openInNative('interview')">🎤 按岗面试</button>
          </template>
          <button type="button" class="rf-btn rf-btn-primary" :disabled="job.status === 'ready'" @click="setJobStatus(job, 'ready')">📮 已投递</button>
          <button type="button" class="rf-btn" :disabled="job.status === 'ready_bishi'" @click="setJobStatus(job, 'ready_bishi')">✍️ 待笔试</button>
          <button v-if="job.status === 'archived'" type="button" class="rf-btn" title="恢复为未处理" @click="setJobStatus(job, 'new')">↩️ 恢复</button>
          <button v-else type="button" class="rf-btn" title="归档：不感兴趣/已无岗位，不再出现在未处理与推荐里（软删除，避免下次搜集又加回来）" @click="archiveJob(job)">🗄 归档</button>
        </span>
      </div>
    </div>

    <div class="rf-muted">🟢 Vue 特性：v-model 表单（搜索/状态筛选）+ computed 派生可见列表与统计 + 收藏乐观更新（失败回滚）</div>
  </div>
</template>

// desktop/renderer/panel-react/src/tabs/Jobs.jsx
// React 版校招 Tab（前端三态并行展示工单任务 2 · S3：岗位列表 + 筛选 + 投递状态）
// 同一数据源与路由（与原 panel-jobs.js 的 loadJobs 同接口）：
//   GET  /api/jobs/recommended（默认，技术岗 + 匹配排序）· GET /api/jobs?status=xxx
//   POST /api/jobs/favorite { id, favorite } · POST /api/jobs/status { id, status }
// ⚛️ React 特性：useDeferredValue 过滤输入 + useMemo 派生筛选/统计（原生是 innerHTML 拼串 + 全量重渲染）
// 范围说明：JD 反推考点/按岗面试等 agent 流程仍走原生渲染层（点按钮切回原生打开），
//   S3 只做"岗位列表 + 筛选 + 投递状态"这条主链路，避免两套实现分叉。
import { useDeferredValue, useEffect, useMemo, useState } from "react";
import { api } from "../api.js";

const DIRECTION_LABEL = { frontend: "前端", agent: "AI Agent", fullstack: "全栈", backend: "后端", algorithm: "算法" };
const STATUS_LABEL = { ready: "📮 已投递", ready_bishi: "✍️ 待笔试", favor: "⭐ 收藏", done: "✅ 已完成", archived: "🗄 已归档", new: "未处理" };
// 状态值与后端枚举一致（lib/jobs.ts setJobStatus 接受 new/ready/ready_bishi/done/archived）——
// 修复（闭环清查）：此前用 "none" → 「未处理」筛选恒空，且与原生面板（new）口径不一致；
// archived 为终态（归档，软删除），可与「恢复」组成闭环
const STATUS_FILTERS = [["", "全部"], ["ready", "📮 已投递"], ["ready_bishi", "✍️ 待笔试"], ["new", "未处理"], ["archived", "🗄 已归档"]];

export function JobsPanel() {
  const [jobs, setJobs] = useState([]);
  const [status, setStatus] = useState("");
  const [onlyFav, setOnlyFav] = useState(false);
  const [q, setQ] = useState("");
  const deferredQ = useDeferredValue(q); // ⚛️ 输入即时，过滤延后
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState("");
  const [openJd, setOpenJd] = useState({}); // id → 展开 JD

  async function load() {
    setBusy(true);
    setErr("");
    try {
      const j = status
        ? await api(`/api/jobs?status=${encodeURIComponent(status)}`)
        : await api("/api/jobs/recommended");
      setJobs(j?.recommended || j?.jobs || []);
    } catch (e) {
      setErr("岗位读取失败：" + String(e?.message || e).slice(0, 80));
      setJobs([]);
    } finally {
      setBusy(false);
    }
  }
  useEffect(() => { load(); }, [status]);

  /** 收藏/取消（同一路由；乐观更新 + 失败回滚并提示） */
  async function toggleFav(job) {
    const next = !job.favorite;
    setJobs((list) => list.map((x) => (x.id === job.id ? { ...x, favorite: next } : x)));
    try {
      await api("/api/jobs/favorite", { method: "POST", body: { id: job.id, favorite: next } });
    } catch (e) {
      setJobs((list) => list.map((x) => (x.id === job.id ? { ...x, favorite: !next } : x)));
      window.kanban?.notify?.("⭐ 收藏失败", String(e?.message || e).slice(0, 60));
    }
  }

  /** 投递状态流转（同一路由） */
  async function setJobStatus(job, next) {
    try {
      await api("/api/jobs/status", { method: "POST", body: { id: job.id, status: next } });
      setJobs((list) => list.map((x) => (x.id === job.id ? { ...x, status: next, appliedAt: next === "ready" ? Date.now() : x.appliedAt } : x)));
      if (next === "archived") window.kanban?.notify?.("🏢 校招岗位", "已归档（筛选里选「🗄 已归档」可恢复）");
    } catch (e) {
      setErr("状态更新失败：" + String(e?.message || e).slice(0, 60));
    }
  }

  /** 归档（消失型操作 → 二次确认；Electron 渲染层 confirm 可用，prompt 会抛异常） */
  function archiveJob(job) {
    if (!window.confirm(`归档「${job.company} ${job.title}」？归档后不再出现在未处理与推荐里。`)) return;
    setJobStatus(job, "archived");
  }

  /** agent 流程（JD 反推考点/按岗面试）复用原生：切回原生渲染层，不重复实现 */
  function openInNative(id, kind) {
    window.switchRenderer?.("jobs", "native");
    const fn = kind === "study" ? window.jobLoopStudy : window.jobLoopInterview;
    if (typeof fn === "function") fn(id);
    else window.kanban?.notify?.("🎨 渲染层", "已切回原生渲染层，请在原生界面继续该操作");
  }

  // ⚛️ 派生：搜索（题目/公司）+ 收藏过滤 + 统计
  const { visible, stats } = useMemo(() => {
    const query = deferredQ.trim().toLowerCase();
    const list = jobs.filter((j) => {
      if (onlyFav && !j.favorite) return false;
      if (!query) return true;
      return `${j.company || ""} ${j.title || ""} ${j.summary || ""}`.toLowerCase().includes(query);
    });
    return {
      visible: list,
      stats: { total: jobs.length, fav: jobs.filter((j) => j.favorite).length, applied: jobs.filter((j) => j.status === "ready").length },
    };
  }, [jobs, deferredQ, onlyFav]);

  return (
    <div className="rf-stack">
      <div className="rf-card">
        <div className="rf-head">
          <b className="rf-title">🏢 校招岗位 · React 版</b>
          <span style={{ display: "flex", gap: 6, alignItems: "center" }}>
            <span className="rf-muted">{stats.total} 个岗位 · 收藏 {stats.fav} · 已投 {stats.applied}</span>
            <button type="button" className="rf-btn" onClick={load} disabled={busy}>{busy ? "刷新中…" : "🔄 刷新"}</button>
          </span>
        </div>
        <div style={{ display: "flex", gap: 6, flexWrap: "wrap", alignItems: "center" }}>
          <input
            className="rf-input rf-grow"
            value={q}
            onChange={(e) => setQ(e.target.value)}
            placeholder="搜索公司 / 岗位 / 摘要…"
            aria-label="搜索岗位"
          />
          <select className="rf-input" value={status} onChange={(e) => setStatus(e.target.value)} aria-label="按投递状态筛选">
            {STATUS_FILTERS.map(([v, label]) => <option key={v} value={v}>{label}</option>)}
          </select>
          <label className="rf-muted" style={{ display: "flex", alignItems: "center", gap: 4 }}>
            <input type="checkbox" checked={onlyFav} onChange={(e) => setOnlyFav(e.target.checked)} aria-label="只看收藏岗位" /> 只看收藏
          </label>
          <button type="button" className="rf-btn" onClick={() => window.switchRenderer?.("jobs", "native")} title="搜集校招等抓取操作在原生渲染层">🔍 搜集校招（原生）</button>
        </div>
        {err && <div className="rf-muted rf-chip-warn" style={{ marginTop: 6 }}>⚠️ {err}</div>}
      </div>

      <div className="rf-card">
        {visible.length === 0 ? (
          <div className="rf-muted">{jobs.length === 0 ? "暂无岗位——点「🔍 搜集校招」（原生）抓取，或先在设置里填简历/方向" : "没有匹配的岗位，试试清空搜索或换筛选"}</div>
        ) : (
          visible.map((job) => (
            <div key={job.id} className="rf-row rf-row-start">
              <span className="rf-grow">
                <span style={{ display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap" }}>
                  <b className="rf-title">{job.company}</b>
                  <span>{job.title}</span>
                  <span className="rf-chip">{DIRECTION_LABEL[job.direction] || job.direction || "未标方向"}</span>
                  <span className="rf-chip rf-chip-info">匹配 {job.match || "—"}</span>
                  {job.favorite && <span className="rf-chip rf-chip-warn">⭐ 收藏</span>}
                  <span className="rf-chip rf-chip-plain">{STATUS_LABEL[job.status] || job.status || "未处理"}</span>
                </span>
                {(job.jobType || job.deadline || job.bishiDate) && (
                  <span className="rf-muted" style={{ display: "block", marginTop: 3 }}>
                    {job.jobType && <span>{job.jobType} </span>}
                    {job.deadline && <span>⏰ 截止 {job.deadline} </span>}
                    {job.bishiDate && <span>📝 笔试 {job.bishiDate}</span>}
                  </span>
                )}
                {job.summary && <span className="rf-muted" style={{ display: "block", marginTop: 3 }}>{job.summary}</span>}
                {job.jdText && openJd[job.id] && (
                  <pre className="rf-report rf-sub" style={{ marginTop: 6 }}>{job.jdText}</pre>
                )}
              </span>
              <span style={{ display: "flex", gap: 4, flexWrap: "wrap", justifyContent: "flex-end" }}>
                <button
                  type="button"
                  className="rf-btn"
                  onClick={() => toggleFav(job)}
                  title={job.favorite ? "取消收藏" : "收藏该岗位"}
                  aria-label={job.favorite ? `取消收藏 ${job.company}` : `收藏 ${job.company}`}
                >{job.favorite ? "⭐" : "☆"}</button>
                {job.jdText && (
                  <button
                    type="button"
                    className="rf-btn"
                    onClick={() => setOpenJd((m) => ({ ...m, [job.id]: !m[job.id] }))}
                    aria-expanded={Boolean(openJd[job.id])}
                  >📋 JD</button>
                )}
                {job.applyUrl && <a className="rf-btn" href={job.applyUrl} target="_blank" rel="noopener noreferrer">🔗 去投递</a>}
                {/* 归档=不感兴趣：不再提供「学考点/按岗面试」（后端按 id 查岗位时也排除了归档行，否则点了必 404） */}
                {job.status !== "archived" && (
                  <>
                    <button type="button" className="rf-btn" onClick={() => openInNative(job.id, "study")} title="从 JD 反推考点加入学习清单（原生流程）">📚 学考点</button>
                    <button type="button" className="rf-btn" onClick={() => openInNative(job.id, "interview")} title="按该岗位 JD 开一场模拟面试（原生流程）">🎤 按岗面试</button>
                  </>
                )}
                <button type="button" className="rf-btn rf-btn-primary" onClick={() => setJobStatus(job, "ready")} disabled={job.status === "ready"}>📮 已投递</button>
                <button type="button" className="rf-btn" onClick={() => setJobStatus(job, "ready_bishi")} disabled={job.status === "ready_bishi"}>✍️ 待笔试</button>
                {job.status === "archived"
                  ? <button type="button" className="rf-btn" onClick={() => setJobStatus(job, "new")} title="恢复为未处理">↩️ 恢复</button>
                  : <button type="button" className="rf-btn" onClick={() => archiveJob(job)} title="归档：不感兴趣/已无岗位，不再出现在未处理与推荐里（软删除，避免下次搜集又加回来）">🗄 归档</button>}
              </span>
            </div>
          ))
        )}
      </div>

      <div className="rf-muted">⚛️ React 特性：useDeferredValue 搜索 + useMemo 派生筛选/统计；抓取与 agent 流程复用原生渲染层（不做两套）</div>
    </div>
  );
}
